### PR TITLE
Fix period documentation

### PR DESCRIPTION
**Pull request by alappe**

### CODE REVIEW

**Comment by kipcole9** [comment]
Thanks very much @alappe, greatly appreciated.  I will publish a new docs version in the next 30 minutes.

**Comment by alappe** [comment]
You're welcome. While I'm at it, I noticed that my formatter didn't agree with the current formatting of the while. Maybe the project needs a reformat as a whole… if not, nevermind.

**Comment by kipcole9** [comment]
I'm not very consistent in my use of the formatter I know. And eventually I need to go all in, or not.    I care a lot about how the code looks, but I don't always agree with the formatter (not unique there I know!).

May I ask what your use case is for this library?   Its one I think should be of more use that it is - probably because people think of it as part of "localisation" rather than "calendars".  So I'm always curious what people use it for - given that I do have a bit of a calendar fetish.

**Comment by alappe** [comment]
I was looking for a simple way to add a month to one Date using the coerce strategy and read that this library is providing this. Since I use a lot of ex_cldr packages already and like them a lot, I opted to use `Calendar.plus/…` as well. Something I could have written by myself easily, but for now your packages always worked perfectly. Haven't looked deeper into it yet.

**Pull request merged**
