### PR TITLE
feat: add to and from MJD conversions

### PR DESCRIPTION
**Pull request by polvalente**
I needed this conversion for parsing some files and couldn't find any lib that did those. Let me know if you want any changes!

### CODE REVIEW

**Comment by kipcole9** [comment]
Much appreciated @polvalente, gratefully accepted. Will push a new version shortly as part of the update cycle to CLDR 42.  I think I implemented an MJD set of functions in Astro but its better they are here for sure.  I'd be interested in your calendaring/astro use case if you're able to share?

**Comment by kipcole9** [comment]
I have just published [ex_cldr_calendars version 1.21.0](https://hex.pm/packages/ex_cldr_calendars/1.21.0) with the following changelog entry:

### Enhancements

* Adds modified Julian days conversions. Thanks to @polvalente for the PR. Closes #14.

Thanks again!

**Comment by polvalente** [comment]
> Much appreciated @polvalente, gratefully accepted. Will push a new version shortly as part of the update cycle to CLDR 42. I think I implemented an MJD set of functions in Astro but its better they are here for sure. I'd be interested in your calendaring/astro use case if you're able to share?

Thanks @kipcole9! The use case is that I'm working on parsing some NetCDF files which contain timestamps represented as MJD floats, and I want to make the values human-readable

**Comment by kipcole9** [comment]
I had to google NetCDF. But having done so and being a distant admirer of all your work on numerical Elixir it makes perfect sense :-)

**Pull request merged**
